### ISSUE TITLE
Exitcode not match

### ISSUE THREAD

**Issue by calmowls** [extism/java-sdk#17]
Following dotnet PDK build a wasm, when throw error or after Pdk.SetError it will return 1. But our Java sdk only throw exception when exitcode is -1. Is this a mismatch or any other consideration? 
I also checked dotnet sdk. It seems first check error message, if the error message is not empty it will throw exception with both exitcode and error message.
Is there any convention under Extism org about this?

**Comment by zshipko** [comment]
Thanks, I think this is a bug - it should check for any non-zero exit code. I will make a PR right now.
