### ISSUE TITLE
The execution time of plugin function is growing up with each new thread

### ISSUE THREAD

**Issue by amysyk-viax-io** [extism/java-sdk#23]
I have a simple project that covers two usecases: http calls and host functions calls. You can find it by the following link https://github.com/amysyk-viax-io/wasm-playground

I am trying to handle a lot of parallel calls to plugin. The first way I do is creating a new plugin for each call. The implementation is under `src/main/java/io/viax/wasmplayground/service/DefaultExtismPluginService.java`. By running the following test `k6/extism-kv-store.js`, I faced with some significant performance degradation when increasing virtual users amount.

Another approach is to use FixedThreadPool with predefined threads `src/main/java/io/viax/wasmplayground/service/ConcurrentExtismPluginService.java`. It works well with small number of threads and quick running calls. But once the execution time of plugin function increased it becomes a bottleneck.

Please let me know if you need more details and thanks in advance for any help here.

**Comment by bhelx** [comment]
Thank you for reporting and giving us a reproducible example! Creating a plugin per call or creating a threadpool are both viable options. For the former, you may want to start by investigating the caching and some of the other environment variables you can use to optimize the underlying wasmtime engine: https://github.com/extism/extism/tree/main/runtime#environment-variables

**Comment by amysyk-viax-io** [comment]
@bhelx Thank you for advice. After playing with cache I found that default values work the best. In general I was experimenting with compression level and worker event queue size.

Another finding, rust plugin runs much faster then js plugin. The only differece is in wasm module size: rust 429KB vs js 1.9M. Below you can find results of `extism-kv-store.js` test. Also I added some logs, where you can see time of execution of each plugin stage.

> js: running 2m39.5s, 1000 iterations in 50 paralel threads

```
DEBUG|15:43:52.187Z|http-nio-8080-exec-32|Plugin: new[3635.443208ms] call[0.965083ms] close[4493.884667ms]
DEBUG|15:43:52.199Z|http-nio-8080-exec-46|Plugin: new[4103.286208ms] call[1.0965ms]   close[3952.816083ms]
DEBUG|15:43:52.203Z|http-nio-8080-exec-29|Plugin: new[4290.585417ms] call[0.924458ms] close[3742.940542ms]
DEBUG|15:43:52.206Z|http-nio-8080-exec-33|Plugin: new[4412.68175ms]  call[0.887667ms] close[3591.915ms]
DEBUG|15:43:52.212Z|http-nio-8080-exec-31|Plugin: new[4766.702333ms] call[0.851083ms] close[3166.778042ms]
DEBUG|15:43:52.213Z|http-nio-8080-exec-50|Plugin: new[4828.828958ms] call[0.787292ms] close[3094.70325ms]
DEBUG|15:43:52.217Z|http-nio-8080-exec-21|Plugin: new[5128.898541ms] call[0.795916ms] close[2716.638042ms]
DEBUG|15:43:52.219Z|http-nio-8080-exec-27|Plugin: new[5425.722542ms] call[0.826125ms] close[2324.342209ms]
DEBUG|15:43:52.222Z|http-nio-8080-exec-10|Plugin: new[5852.966875ms] call[0.833542ms] close[1813.552125ms]
DEBUG|15:43:52.225Z|http-nio-8080-exec-23|Plugin: new[6714.729166ms] call[0.894709ms] close[785.227125ms]
```

> rust: running 0m09.6s, 1000 iterations in 50 paralel threads

```
DEBUG|15:49:23.230Z|http-nio-8080-exec-19|Plugin: new[167.043333ms] call[0.285625ms] close[285.319666ms]
DEBUG|15:49:23.231Z|http-nio-8080-exec-12|Plugin: new[177.350333ms] call[0.254833ms] close[273.924833ms]
DEBUG|15:49:23.231Z|http-nio-8080-exec-29|Plugin: new[173.919708ms] call[0.343208ms] close[274.042667ms]
DEBUG|15:49:23.232Z|http-nio-8080-exec-24|Plugin: new[171.316709ms] call[0.321666ms] close[251.5255ms]
DEBUG|15:49:23.233Z|http-nio-8080-exec-9 |Plugin: new[177.411208ms] call[0.257541ms] close[241.389583ms]
DEBUG|15:49:23.233Z|http-nio-8080-exec-14|Plugin: new[181.532458ms] call[0.342041ms] close[235.805584ms]
DEBUG|15:49:23.234Z|http-nio-8080-exec-38|Plugin: new[192.911458ms] call[0.290666ms] close[220.114959ms]
DEBUG|15:49:23.235Z|http-nio-8080-exec-28|Plugin: new[218.17275ms]  call[0.343958ms] close[187.629042ms]
DEBUG|15:49:23.235Z|http-nio-8080-exec-39|Plugin: new[237.79425ms]  call[0.299291ms] close[157.253667ms]
DEBUG|15:49:23.235Z|http-nio-8080-exec-8 |Plugin: new[238.987791ms] call[0.24475ms]  close[155.756458ms]
```

For some reason, creation of plugin and removing it from the registry take much more time then function call.

Please let me know if there is something else I can take a look at host/guest level or if it is a runtime specific issue.

**Comment by bhelx** [comment]
> For some reason, creation of plugin and removing it from the registry take much more time then function call.

The reason here is compilation. In wasmtime, when you load the plugin, it is compiled from Wasm to native code all in one go. It's effectively an optimized AOT compile step. They are working on JIT support but it is not ready. In the meantime the best you can do is cache the compiled modules so you don't re-compile them. That's what the cache setting is doing. it's storing the native code on disk. it can still be quite large too, bigger than the wasm, but obvioulsy just needs to be loaded an not re-compiled so it's generally faster. the best way to manage the problem is keep the plugins alive as long as possible and re-use them, if you can safely.

**Comment by bhelx** [comment]
Feel free to re-open if you still feel we're missing something!
